### ISSUE TITLE
Dispatcher code trace dependency

### ISSUE THREAD

**Issue by pha123661** [chiluen/springframework-webmvc-servlet#1]
我發現 dispatcher 跟大約一半的 handler 都在現在我們分的 remainfiles 裡面，
這些檔案還蠻多行的，然後 handler 似乎要從這邊開始看，所以我在想有沒有需要直接合併一起看？
不過可能你要改一下看的順序

Note: 有這些檔案
![image (1)](https://user-images.githubusercontent.com/69206824/228164458-990c3bc1-a4b8-49fe-bb69-582c66963811.png)
![image](https://user-images.githubusercontent.com/69206824/228164468-ab39c03c-acb5-405e-88dd-3f5327c91d3c.png)

**Comment by chiluen** [comment]
那我先從remainfiles的Handler相關的程式碼開始看，並且寫README幫助你理解，感謝提出這個Issue
